


Context
— none fetched
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.configuration }}

  test-math-operations:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.configuration }}
    - name: Test MathOperations
      run: dotnet test --no-build --verbosity normal --configuration ${{ matrix.configuration }} --filter "FullyQualifiedName~MathOperationTests"

  test-custom-stack:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.configuration }}
    - name: Test CustomStack
      run: dotnet test --no-build --verbosity normal --configuration ${{ matrix.configuration }} --filter "FullyQualifiedName~CustomStackTests"

  test-reservation:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.configuration }}
    - name: Test Reservation
      run: dotnet test --no-build --verbosity normal --configuration ${{ matrix.configuration }} --filter "FullyQualifiedName~ReservationTests"

  test-html-format-helper:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.configuration }}
    - name: Test HtmlFormatHelper
      run: dotnet test --no-build --verbosity normal --configuration ${{ matrix.configuration }} --filter "FullyQualifiedName~HtmlFormatHelperTests"